TasksManagementSystem/TasksManagementSystem/ViewModels/TaskDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static TaskManagementSystem.Data.Helpers.Enums;

namespace TasksManagementSystem.ViewModels
{
    public class TaskDetailsViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string TaskTitle { get; set; }

        [Display(Name = "Required by date")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? RequiredByDate { get; set; }

        [Display(Name = "Created date")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Created by")]
        public string AuthorName { get; set; }

        public TaskStatus Status { get; set; }

        public string StatusString
        {
            get
            {
                return this.Status.ToString();
            }
        }

        public TaskType Type { get; set; }

        public string TypeString
        {
            get
            {
                return this.Type.ToString();
            }
        }

        [Display(Name = "Assigned to")]
        public string AssignedTo { get; set; }

        [Display(Name = "Next action date")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? NextActionDate { get; set; }


        public string Description { get; set; }

        public IEnumerable<CommentViewModel> Comments { get; set; }

        [Required]
        [DisplayName("Type")]
        public int CommentTypeId { get; set; }

        public IEnumerable<SelectListItem> CommentTypes { get; set; }

        [Display(Name = "Reminder date")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? CommentReminderDate { get; set; }

        [Required]
        public string Comment { get; set; }
    }
}

TasksManagementSystem/TasksManagementSystem/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TasksManagementSystem.Controllers
{
    public class TaskController : Controller
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }
    }
}

TasksManagementSystem/TasksManagementSystem/Controllers/TasksController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TaskManagementSystem.Models;
using TasksManagementSystem.ViewModels;
using static TaskManagementSystem.Data.Helpers.Enums;

namespace TasksManagementSystem.Controllers
{
    [Authorize]
    public class TasksController : BaseController
    {
        [HttpGet]
        public ActionResult Add()
        {
            List<SelectListItem> listOfUsers = new List<SelectListItem>();
            listOfUsers.Insert(0, (new SelectListItem { Text = "Ivan", Value = "0" }));
            listOfUsers.Insert(1, (new SelectListItem { Text = "Petyr", Value = "1" }));
            listOfUsers.Insert(2, (new SelectListItem { Text = "Hristiyan", Value = "2" }));

            TaskAddViewModel model = new TaskAddViewModel();        
            model.AssignedToList = listOfUsers;
            model.Statuses = LoadStatusesFromEnumeration();
            model.Types = LoadTypesFromEnumeration();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Create")]
        public ActionResult Add(TaskAddViewModel taskVM)
        {
            List<SelectListItem> listOfUsers = new List<SelectListItem>();
            listOfUsers.Insert(0, (new SelectListItem { Text = "Ivan", Value = "0" }));
            listOfUsers.Insert(1, (new SelectListItem { Text = "Petyr", Value = "1" }));
            listOfUsers.Insert(2, (new SelectListItem { Text = "Hristiyan", Value = "2" }));

            if (ModelState.IsValid && taskVM != null)
            {
                Tasks task = new Tasks();
                task.Title = taskVM.TaskTitle;
                task.AuthorName = User.Identity.Name;
                task.CreatedDate = DateTime.Now;
                task.RequiredByDate = taskVM.RequiredByDate;
                task.Status = (TaskStatus)Convert.ToInt32(taskVM.StatusId);
                task.Type = (TaskType)Convert.ToInt32(taskVM.TypeId);
                task.Description = taskVM.Description;
                task.AssignedTo = (from e in listOfUsers
                                   where e.Value == taskVM.AssignedToValue
                                   select e.Text
                                   ).FirstOrDefault();

                this.Data.Tasks.Add(task);
                this.Data.SaveChanges();

                return RedirectToAction("TasksList");
            }

            taskVM.Statuses = LoadStatusesFromEnumeration();
            taskVM.Types = LoadTypesFromEnumeration();
            taskVM.AssignedToList = listOfUsers;

            return View(taskVM);
        }

        public ActionResult TasksList()
        {
            var tasks = (from task in this.Data.Tasks.GetAll().ToList()
                         select new TaskHomeViewModel()
                         {
                             Id = task.Id,
                             RequiredByDate = task.RequiredByDate,
                             Status = task.Status,
                             Type = task.Type,
                             AssignedTo = task.AssignedTo,
                             TaskTitle = task.Title
                         });
            return View(tasks);
        }

        public ActionResult TaskDetails(int id)
        {
            var commentReminders = (from comment in this.Data.Comments.GetAll().ToList()
                                    where comment.TaskId == id && comment.ReminderDate != null
                                    select comment.ReminderDate
                         ).OrderBy(o=>o.Value);
            var viewModel = this.Data.Tasks.GetAll().Where(x => x.Id == id)
                .Select(x => new TaskDetailsViewModel
                {
                    Id = x.Id,
                    TaskTitle = x.Title,
                    CreatedDate = x.CreatedDate,
                    RequiredByDate = x.RequiredByDate,
                    Status = x.Status,
                    Type = x.Type,
                    AssignedTo = x.AssignedTo,
                    NextActionDate = commentReminders.FirstOrDefault(),
                    Description = x.Description,
                    CommentTypes = LoadCommentTypesFromEnumeration(),
                    AuthorName =  x.AuthorName,                  
                    Comments = x.Comments.Select(y => new CommentViewModel {
                        Id = y.Id,
                        AuthorUsername = y.AuthorName,
                        Content = y.Content,
                        DateAdded = y.DateAdded,
                        ReminderDate = y.ReminderDate,
                        Type = y.Type
                    }),
                }).FirstOrDefault();

            return View(viewModel);
        }

        [ValidateAntiForgeryToken]
        public ActionResult PostComment(SubmitCommentViewModel commentModel)
        {
            if (ModelState.IsValid)
            {           
                this.Data.Comments.Add(new Comment()
                {
                    AuthorName = User.Identity.GetUserName(),
                    Content = commentModel.Comment,
                    TaskId = commentModel.TaskId,
                    DateAdded = DateTime.Now,
                    ReminderDate = commentModel.CommentReminderDate,
                    Type = (CommentType)Convert.ToInt32(commentModel.CommentTypeId)
                });

                this.Data.SaveChanges();
                return RedirectToAction("TaskDetails", new { id = commentModel.TaskId } );
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest, ModelState.Values.First().ToString());
        }

        public ActionResult Dashboard()
        {
            var tasks = (from task in this.Data.Tasks.GetAll().ToList()
                         select new TaskHomeViewModel()
                         {
                             Id = task.Id,
                             TaskTitle = task.Title,
                             RequiredByDate = task.RequiredByDate,
                             Status = task.Status,
                             Type = task.Type,
                             AssignedTo = task.AssignedTo
                         });
            return View(tasks);
        }

        #region LoadFromEnums
        private static List<SelectListItem> LoadStatusesFromEnumeration()
        {
            var statuses = new List<SelectListItem>();

            for (int i = 0; i < Enum.GetValues(typeof(TaskStatus)).Length; i++)
            {
                var item = new SelectListItem
                {
                    Text = ((TaskStatus)i).ToString(),
                    Value = (i).ToString()
                };

                if (((TaskStatus)i).ToString() == "Created")
                {
                    item.Selected = true;
                }

                statuses.Add(item);
            }

            return statuses;
        }

        private static List<SelectListItem> LoadTypesFromEnumeration()
        {
            var types = new List<SelectListItem>();

            for (int i = 0; i < Enum.GetValues(typeof(TaskType)).Length; i++)
            {
                var item = new SelectListItem
                {
                    Text = ((TaskType)i).ToString(),
                    Value = (i).ToString()
                };

                if (((TaskType)i).ToString() == "Development")
                {
                    item.Selected = true;
                }

                types.Add(item);
            }

            return types;
        }

        private static List<SelectListItem> LoadCommentTypesFromEnumeration()
        {
            var commentTypes = new List<SelectListItem>();

            for (int i = 0; i < Enum.GetValues(typeof(CommentType)).Length; i++)
            {
                var item = new SelectListItem
                {
                    Text = ((CommentType)i).ToString(),
                    Value = (i).ToString()
                };

                if (((CommentType)i).ToString() == "Ordinary")
                {
                    item.Selected = true;
                }

                commentTypes.Add(item);
            }

            return commentTypes;
        }

        #endregion
    }
}

TasksManagementSystem/TasksManagementSystem/Views/Tasks/Add.cshtml
@model TasksManagementSystem.ViewModels.TaskAddViewModel
@{
    ViewBag.Title = "Add";
}

<h2>Add task</h2>
<hr />

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>

@using (Html.BeginForm("Add", "Tasks", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskTitle)
        </dt>
        <dd>
            @Html.EditorFor(model => model.TaskTitle)
            @Html.ValidationMessageFor(model => model.TaskTitle, "", new { @class = "text-danger" })
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RequiredByDate)
        </dt>
        <dd>
            @Html.TextBoxFor(model => model.RequiredByDate, new { @class = "datepick", @readonly = "readonly", required = "required" })
            @Html.ValidationMessageFor(model => model.RequiredByDate, "", new { @class = "text-danger" })
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd>
            @Html.DropDownListFor(model => model.StatusId, Model.Statuses, new { @class = "formDDL" })
            @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeId)
        </dt>
        <dd>
            @Html.DropDownListFor(model => model.TypeId, Model.Types, new { @class = "formDDL" })
            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AssignedToValue)
        </dt>
        <dd>
            @Html.DropDownListFor(model => model.AssignedToValue, Model.AssignedToList, new { @class = "formDDL" })
            @Html.ValidationMessageFor(model => model.AssignedToValue, "", new { @class = "text-danger" })
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </dd>
    </dl>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
}
<br />
<div>
    <button type="submit" class="btn btn-primary" onclick="@("window.location.href='" + @Url.Action("TasksList", "Tasks") + "'");">
        <i class="glyphicon glyphicon-arrow-left"></i> Back
    </button>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $('.datepick').datepicker({
            buttonImage: "http://www.effinghamparkdistrict.org/graphics/calendar_icon.png",
            buttonImageOnly: true,
            changeMonth: true,
            changeYear: true,
            buttonText: "Choose date",
            showOn: 'both',
            dateFormat: 'yy-mm-dd'
        });
    </script>

}

TasksManagementSystem/TasksManagementSystem/Views/Tasks/Dashboard.cshtml
@model IEnumerable<TasksManagementSystem.ViewModels.TaskHomeViewModel>
@{
    ViewBag.Title = "Dashboard";
}

<h2>Tasks dashboard</h2>
<hr />


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>


@if (Model != null)
{
    <table class="dataTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TaskTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RequiredByDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AssignedTo)
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequiredByDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssignedTo)
                    </td>
                    <td style="width:70px;">
                        <a href="@Url.Action("TaskDetails", new { id = item.Id })" title="Details">
                            <i class="glyphicon glyphicon-info-sign"></i>
                            <span class="sr-only">Details</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

@section Scripts{
    <script>
        var oTable = $('.dataTable').dataTable({
            "lengthChange": false
        });

        $("<br /><br /><br />").prependTo('div.dataTables_filter');
        $("<div class='nBreak padR'>&nbsp;&nbsp;From <input id='min' type='text' class='datepick' readonly = 'readonly' />&nbsp;To <input id='max' type='text' class='datepick' readonly = 'readonly' /></div>").prependTo('div.dataTables_filter');
        $("<input type='button' value = 'Clear dates' class='btn btn-primary' id='clear-dates' background-color = '#286090 '>").prependTo('div.dataTables_filter ');

        $("<label for='dashboard' style='float:left;color:#004d99;font-style: italic;font-size:large'>Tasks for period:</label>").prependTo('div.dataTables_filter');

        $('.datepick').datepicker({
            showOn: "both",
            buttonImage: "http://www.effinghamparkdistrict.org/graphics/calendar_icon.png",
            dateFormat: "yy-mm-dd",
        });

        $('#min').datepicker("option", "onSelect", function (dateString) {
            $("#max").datepicker('option', 'minDate', dateString),
            oTable.fnDraw();
        });


        $('#max').datepicker("option", "onSelect", function (dateString) {
            $("#min").datepicker('option', 'maxDate', dateString),
            oTable.fnDraw();
        });


        $.fn.dataTableExt.afnFiltering.push(
            function (oSettings, aData, iDataIndex) {
                var iMin = document.getElementById('min').value;
                var iMax = document.getElementById('max').value;

                if (iMin == null || iMin == "") {
                    return true;
                }
                if (iMax == null || iMax == "") {
                    return true;
                }

                var minDate = new Date(iMin);
                var maxDate = new Date(iMax);

                var date = new Date(aData[1]);

                if (minDate <= date && date <= maxDate) {
                    return true;
                }
                return false;
            }
        );

        var $dates = $('#min, #max');
        $('#clear-dates').on("click", function () {
            $("#min").datepicker('option', 'maxDate', null),
            $("#max").datepicker('option', 'minDate', null),
            $dates.datepicker('setDate', null);
            oTable.fnDraw();
        });

    </script>
}

TasksManagementSystem/TasksManagementSystem/Views/Tasks/TaskDetails.cshtml
@model TasksManagementSystem.ViewModels.TaskDetailsViewModel
@{
    ViewBag.Title = "Details";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>

<h2>Details</h2>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.TaskTitle)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.TaskTitle)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.AuthorName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.AuthorName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.CreatedDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.CreatedDate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RequiredByDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RequiredByDate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.AssignedTo)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.AssignedTo)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Status)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Status)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Type)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Type)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>
    @if (Model.NextActionDate != null)
    {
        <dt>
            @Html.DisplayNameFor(model => model.NextActionDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NextActionDate)
        </dd>
    }  
</dl>

<hr />
<div id="Comments">
    <h4>Comments section</h4>
    <hr />
    @foreach (var comment in Model.Comments)
    {
        @Html.Partial("_CommentPartial", comment)
    }
    <br />
</div>
@if (User.Identity.IsAuthenticated)
{
    using (Ajax.BeginForm("PostComment", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "Comments", OnFailure = "commentPostFailure" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("TaskId", Model.Id)
        <div class="dvComment">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Comment)
                </dt>
                <dd>
                    @Html.TextAreaFor(model => model.Comment, new { placeholder = "Comment content", @class = "commentTextArea" })
                    @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                </dd>              
                    <dt>
                        @Html.DisplayNameFor(model => model.CommentReminderDate)
                    </dt>
                    <dd>
                        @Html.TextBoxFor(model => model.CommentReminderDate, new { @class = "datepick", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.CommentReminderDate, "", new { @class = "text-danger" })
                    </dd>            
                <dt>
                    @Html.DisplayNameFor(model => model.CommentTypeId)
                </dt>
                <dd>
                    @Html.DropDownListFor(model => model.CommentTypeId, Model.CommentTypes, new { @class = "formDDL" })
                    @Html.ValidationMessageFor(model => model.CommentTypeId, "", new { @class = "text-danger" })
                </dd>
            </dl>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit comment" class="btn btn-primary" />
            </div>
        </div>
    }
    <br />
    <button type="submit" class="btn btn-primary" onclick="@("window.location.href='" + @Url.Action("TasksList", "Tasks") + "'");">
        <i class="glyphicon glyphicon-arrow-left"></i> Back
    </button>
}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $('.datepick').datepicker({
            buttonImage: "http://www.effinghamparkdistrict.org/graphics/calendar_icon.png",
            buttonImageOnly: true,
            changeMonth: true,
            changeYear: true,
            buttonText: "Choose date",
            showOn: 'both',
            dateFormat: 'yy-mm-dd'
        });

        function commentPostFailure() {
            alert("Error");
        }

    </script>
}

TasksManagementSystem/TasksManagementSystem/Views/Tasks/TasksList.cshtml
@model IEnumerable<TasksManagementSystem.ViewModels.TaskHomeViewModel>
@{
    ViewBag.Title = "TasksList";
}

<h2>List of Tasks</h2>
<hr />

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>


@if (Model != null)
{
    <table class="dataTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TaskTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RequiredByDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AssignedTo)
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequiredByDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssignedTo)
                    </td>
                    <td style="width:70px;">
                        <a href="@Url.Action("TaskDetails", new { id = item.Id })" title="Details">
                            <i class="glyphicon glyphicon-info-sign"></i>
                            <span class="sr-only">Details</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

@section Scripts{
    <script>
        var oTable = $('.dataTable').dataTable();
    </script>
}